[package]
name = "find-slow-sectors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.10"
color-eyre = "0.6.2"
rusqlite = "0.28.0"
